### ISSUE TITLE
Make it play well with Japanese / Chinese input method

### ISSUE THREAD

**Issue by victorteokw** [cheunghy/jquery.colorfy#1]
![screen shot 2015-04-04 at 10 40 20 pm](https://cloud.githubusercontent.com/assets/3055936/6993091/a53df2f2-db1b-11e4-97fd-b026f700023f.png)

**Comment by victorteokw** [comment]
With `keypress` and `input`, it plays quite well now. Will publish a new version contains fix for this.

**Comment by XHTeng** [comment]
not fix
