### ISSUE TITLE
Using colorfy with two <input> fields eats the second class

### ISSUE THREAD

**Issue by dertuxmalwieder** [cheunghy/jquery.colorfy#12]
I have two colorfy'd `input` fields, one with `class="l"`, one with `class="r"`.

The resulting `div`s both have the class `l`. That makes things difficult. :-/

**Comment by victorteokw** [comment]
update to version 0.0.5 should fix this issue

**Comment by dertuxmalwieder** [comment]
Confirmed, thanks.
