### ISSUE TITLE
Respect the `input` value changing

### ISSUE THREAD

**Issue by dertuxmalwieder** [cheunghy/jquery.colorfy#13]
I am currently writing some script which calculates things from the left `input` field and puts the results into the right `input` field. `colorfy` does not seem to apply the changes though: Changing the `input value` programmatically does not update the `colorfy div`. Can I, somehow, force it to do so?

**Comment by victorteokw** [comment]
Does version 0.0.6 fix for you?

**Comment by dertuxmalwieder** [comment]
Changing the left `input` field completely breaks `colorfy`...

> TypeError: t.nextSibling is null

**Comment by victorteokw** [comment]
What did you do?

**Comment by dertuxmalwieder** [comment]
I cleared the `input` field to see if that changes the second field. Up to now I see no change yet. :(

(Sleep for a while, will report back later. Thanks already!)

**Comment by victorteokw** [comment]
With version 0.0.7, this should work:

``` javascript
     $('input.l').on("change", function(){
       $('input.r').val($('input.l').val()).trigger("change");
     });
```

**Comment by dertuxmalwieder** [comment]
Yes, the updated version works, thanks. :-)
