### ISSUE TITLE
Update to 0.0.8 brings a new issue ...

### ISSUE THREAD

**Issue by dertuxmalwieder** [cheunghy/jquery.colorfy#14]
... in Firefox: "TypeError: n.innerText is undefined".

**Comment by victorteokw** [comment]
I am sorry about that.

Use 0.0.9 instead.

Since use Firefox to open http://cheunghy.github.io/jquery.colorfy/
doesn't have this issue.

It should be fixed.

Please open issue if you find another bug.

Thanks very much.
